### PR TITLE
Fix wrapping for line containing regular and formatted text

### LINKED ISSUE #24: Link description text does not word wrap
The link description text (the one inside of [ ] ) is broken / split  and does not word wrap.  I have a single word for the description text and it gets split 

See the attached screenshot where the single word "online" is split
image

### PR DESCRIPTION
**Pull request by abdullah-radwan**
Hello!

I noticed that the text wrapping doesn't work properly if a line contains combination of regular and formatted text.

image

Implementing the same code used to fix #24 in the RenderTextWrapped method fixes the issue. I moved its definition below so as to have access to the IsCharInsideWord function. This is the result after:

image

### CODE REVIEW

**Comment by dougbinks** [comment]
Many thanks for the PR, I'll take a look as soon as I get some time.

File: imgui_markdown.h [hunk 1]
```diff
@@ -917,6 +876,72 @@ namespace ImGui
         return c_ != ' ' && c_ != '.' && c_ != ',' && c_ != ';' && c_ != '!' && c_ != '?' && c_ != '\"';
     }
 
+    // ImGui::TextWrapped will wrap at the starting position
+    // so to work around this we render using our own wrapping for the first line
+    inline void TextRegion::RenderTextWrapped( const char* text_, const char* text_end_, bool bIndentToHere_ )
+    {
+    #if IMGUI_VERSION_NUM >= 19197
```
Comment (dougbinks) [inline imgui_markdown.h]: Could you indent macros the same way as any other code? This is the style used in the previous/rest of the code (this is not a PR breaking issue, I can reformat after merge).

**Comment by dougbinks** [comment]
Testing with `IMGUI_VERSION_NUM >= 19197` works, I've not tested with earlier versions but it looks like there is a bug in the code as noted in the review. If you can fix that I'll merge, if you don't have time I can fix it and merge but it will take a little more time!

**Comment by abdullah-radwan** [comment]
Can you explain what the bug is? I don't see anything in the review (unless I am looking at the wrong place)

**Comment by dougbinks** [comment]
If you scroll up on the Github page for the PR showing this comment you should see them.

The issue is these lines: https://github.com/enkisoftware/imgui_markdown/pull/39/files/d583bbc3ab2fdd9768616cdd87fc2deb880fc929#diff-060f48edd26adbd1a019b102a9e5c0cd065f1ae914e6d99002f28fb4b9aed9eeR905-R908

Line 908 uses:
```C
const char* endNextLine = ImGui::GetFont()->CalcWordWrapPositionA( scale, text_, text_end_, widthLeft );
```
but I think it should be:
```C
const char* endNextLine = ImGui::GetFont()->CalcWordWrapPositionA( scale, text_, text_end_, widthNextLine );
```

**Comment by abdullah-radwan** [comment]
Fixed in both methods. Thanks!

**Comment by dougbinks** [comment]
Thanks! Apologies for introducing this bug in the first place :) I'll re-test and merge later on.

**Comment by dougbinks** [comment]
Merged, many thanks!
